# Generated by Django 4.0.6 on 2022-07-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('div', models.CharField(max_length=32)),
                ('labelKor', models.CharField(max_length=128)),
                ('syntax', models.CharField(max_length=256)),
                ('changeIn', models.BooleanField(default=False)),
                ('inspectResults', models.JSONField(blank=True, null=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'account_ratio',
            },
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockCode', models.CharField(max_length=6, unique=True)),
                ('corpCode', models.CharField(blank=True, max_length=8, null=True)),
                ('corpName', models.CharField(max_length=128)),
                ('industry', models.CharField(blank=True, max_length=128, null=True)),
                ('product', models.CharField(blank=True, max_length=128, null=True)),
                ('ceo', models.CharField(blank=True, max_length=128, null=True)),
                ('homepage', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('market', models.CharField(blank=True, max_length=6, null=True)),
                ('fye', models.IntegerField(blank=True, null=True)),
                ('listedAt', models.DateField(blank=True, null=True)),
                ('delistedAt', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corp',
                'ordering': ['-listedAt'],
            },
        ),
        migrations.CreateModel(
            name='CorpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeIn', models.CharField(max_length=16)),
                ('prevValue', models.CharField(max_length=128)),
                ('updatedAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corp_history',
                'get_latest_by': 'updatedAt',
            },
        ),
        migrations.CreateModel(
            name='Fs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.IntegerField()),
                ('bq', models.IntegerField()),
                ('fqe', models.DateField()),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fs',
                'get_latest_by': 'fqe',
            },
        ),
        migrations.CreateModel(
            name='FsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNm', models.CharField(max_length=256)),
                ('labelEng', models.CharField(max_length=256)),
                ('labelKor', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'fsaccount',
            },
        ),
        migrations.CreateModel(
            name='FsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=256)),
                ('labelKor', models.CharField(max_length=256)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'fsdetail',
                'get_latest_by': 'createdAt',
            },
        ),
        migrations.CreateModel(
            name='FsDetailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevValue', models.BigIntegerField(blank=True, null=True)),
                ('updatedAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fsdetail_history',
                'get_latest_by': 'updatedAt',
            },
        ),
        migrations.CreateModel(
            name='FsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=8)),
                ('method', models.CharField(max_length=32)),
                ('oc', models.CharField(max_length=3)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fstype',
            },
        ),
        migrations.CreateModel(
            name='OpendartFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.IntegerField()),
                ('bq', models.IntegerField()),
                ('type', models.CharField(max_length=8)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opendart_file',
            },
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('market', models.CharField(max_length=6)),
                ('price', models.IntegerField()),
                ('side', models.CharField(max_length=1)),
                ('volume', models.IntegerField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='dashboard.corp')),
            ],
            options={
                'db_table': 'tick',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('market', models.CharField(max_length=6)),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('volume_m', models.IntegerField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='dashboard.corp')),
            ],
            options={
                'db_table': 'minute',
                'get_latest_by': 'datetime',
            },
        ),
        migrations.AddIndex(
            model_name='fstype',
            index=models.Index(fields=['name'], name='fstype_name_9b3838_idx'),
        ),
        migrations.AddField(
            model_name='fsdetailhistory',
            name='fd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.fsdetail'),
        ),
        migrations.AddField(
            model_name='fsdetail',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dashboard.fsaccount'),
        ),
        migrations.AddField(
            model_name='fsdetail',
            name='fs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dashboard.fs'),
        ),
        migrations.AddField(
            model_name='fsdetail',
            name='matched',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nstd_siblings', to='dashboard.fsaccount'),
        ),
        migrations.AddField(
            model_name='fsdetail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nstd_childs', to='dashboard.fsaccount'),
        ),
        migrations.AddField(
            model_name='fsaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std_childs', to='dashboard.fsaccount'),
        ),
        migrations.AddField(
            model_name='fsaccount',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='dashboard.fstype'),
        ),
        migrations.AddField(
            model_name='fs',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fs', to='dashboard.corp'),
        ),
        migrations.AddField(
            model_name='fs',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.fstype'),
        ),
        migrations.AddField(
            model_name='corphistory',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.corp'),
        ),
        migrations.AddIndex(
            model_name='corp',
            index=models.Index(fields=['stockCode', 'corpCode', 'industry', 'listedAt'], name='corp_stockCo_36cfd9_idx'),
        ),
        migrations.AddIndex(
            model_name='fsdetail',
            index=models.Index(fields=['accountId', 'fs', 'account'], name='fsdetail_account_3979b5_idx'),
        ),
        migrations.AddIndex(
            model_name='fsaccount',
            index=models.Index(fields=['accountNm', 'type'], name='fsaccount_account_a29384_idx'),
        ),
        migrations.AddIndex(
            model_name='fs',
            index=models.Index(fields=['corp', 'type', 'by', 'bq'], name='fs_corp_id_71d20e_idx'),
        ),
    ]
