# Generated by Django 4.0.6 on 2022-07-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountRatio',
        ),
        migrations.RemoveField(
            model_name='corphistory',
            name='corp',
        ),
        migrations.RemoveField(
            model_name='fs',
            name='corp',
        ),
        migrations.RemoveField(
            model_name='fs',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fsaccount',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='fsaccount',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fsdetail',
            name='account',
        ),
        migrations.RemoveField(
            model_name='fsdetail',
            name='fs',
        ),
        migrations.RemoveField(
            model_name='fsdetail',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='fsdetail',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='fsdetailhistory',
            name='fd',
        ),
        migrations.RemoveField(
            model_name='minute',
            name='corp',
        ),
        migrations.DeleteModel(
            name='OpendartFile',
        ),
        migrations.RemoveField(
            model_name='tick',
            name='corp',
        ),
        migrations.DeleteModel(
            name='Corp',
        ),
        migrations.DeleteModel(
            name='CorpHistory',
        ),
        migrations.DeleteModel(
            name='Fs',
        ),
        migrations.DeleteModel(
            name='FsAccount',
        ),
        migrations.DeleteModel(
            name='FsDetail',
        ),
        migrations.DeleteModel(
            name='FsDetailHistory',
        ),
        migrations.DeleteModel(
            name='FsType',
        ),
        migrations.DeleteModel(
            name='Minute',
        ),
        migrations.DeleteModel(
            name='Tick',
        ),
    ]
