# Generated by Django 4.0.6 on 2022-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_accountratio_remove_corphistory_corp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=256)),
            ],
        ),
    ]
