# Generated by Django 4.0.6 on 2022-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0006_remove_fs_cs_test'),
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaCrossSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('oc', models.CharField(max_length=3)),
                ('market', models.CharField(max_length=6)),
                ('tp', models.DateField()),
                ('updatedAt', models.DateField(auto_now_add=True)),
                ('source', models.ManyToManyField(to='ggdb.fsdetail')),
            ],
            options={
                'db_table': 'fa_cs',
            },
        ),
    ]
