# Generated by Django 4.0.6 on 2022-09-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0008_fsaccountlite_accountratio_items'),
        ('dashboard', '0004_facrosssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_ts', to='ggdb.corp')),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts', to='ggdb.fsaccountlite')),
            ],
            options={
                'db_table': 'fa_ts',
            },
        ),
        migrations.DeleteModel(
            name='FaCrossSection',
        ),
    ]
