# Generated by Django 4.0.6 on 2022-09-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0008_fsaccountlite_accountratio_items'),
        ('dashboard', '0005_fatimeseries_delete_facrosssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaCrossSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=6)),
                ('tp', models.DateField()),
                ('updatedAt', models.DateField(auto_now_add=True)),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs', to='ggdb.fsaccountlite')),
                ('source', models.ManyToManyField(to='ggdb.fsdetail')),
            ],
            options={
                'db_table': 'fa_cs',
            },
        ),
    ]
