# Generated by Django 4.0.6 on 2022-10-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_faroot_faproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faproduct',
            table='fa_product',
        ),
    ]
