# Generated by Django 4.0.6 on 2022-10-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_faproduct_faitem_faitemetc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faitem',
            table='fa_item',
        ),
    ]
