# Generated by Django 4.0.6 on 2022-10-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_faitem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faitem',
            old_name='name',
            new_name='nm',
        ),
        migrations.RenameField(
            model_name='faitemetc',
            old_name='name',
            new_name='nm',
        ),
    ]
