# Generated by Django 4.0.6 on 2022-10-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_name_faitem_nm_rename_name_faitemetc_nm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaItemEtc',
        ),
    ]
