# Generated by Django 4.0.6 on 2022-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_delete_faitemetc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=256)),
                ('lk', models.CharField(max_length=256)),
                ('oc', models.CharField(max_length=3)),
                ('syntax', models.TextField()),
                ('item', models.ManyToManyField(to='dashboard.faitem')),
            ],
            options={
                'db_table': 'fa_ratio',
            },
        ),
        migrations.CreateModel(
            name='FaItemEtc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=256)),
                ('lk', models.CharField(max_length=256)),
                ('oc', models.CharField(max_length=3)),
                ('syntax', models.TextField()),
                ('item', models.ManyToManyField(to='dashboard.faitem')),
            ],
            options={
                'db_table': 'fa_item_etc',
            },
        ),
    ]
