# Generated by Django 4.0.6 on 2022-10-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_faratio_faitemetc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(choices=[('VALUE', '값'), ('RATIO', '비율')], max_length=5)),
                ('nm', models.CharField(max_length=256)),
                ('lk', models.CharField(max_length=256)),
                ('oc', models.CharField(max_length=3)),
                ('syntax', models.TextField()),
                ('item', models.ManyToManyField(to='dashboard.faitem')),
                ('item_self', models.ManyToManyField(to='dashboard.faproduct')),
            ],
            options={
                'db_table': 'fa_product',
            },
        ),
        migrations.RemoveField(
            model_name='faratio',
            name='item',
        ),
        migrations.DeleteModel(
            name='FaItemEtc',
        ),
        migrations.DeleteModel(
            name='FaRatio',
        ),
    ]
