# Generated by Django 4.0.6 on 2022-10-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_faproduct_remove_faratio_item_delete_faitemetc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaProduct',
        ),
    ]
