# Generated by Django 4.0.6 on 2022-10-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_faproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faproduct',
            name='item_self',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.faproduct'),
        ),
    ]
