# Generated by Django 4.0.6 on 2022-10-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_faproduct_item_self'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaProduct',
        ),
    ]
