# Generated by Django 4.0.6 on 2022-10-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_faproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaProduct',
        ),
    ]
