# Generated by Django 4.0.6 on 2022-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_faproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='faproduct',
            name='abbrev',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
