# Generated by Django 4.0.6 on 2022-10-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_faproduct_abbrev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaProduct',
        ),
    ]
