# Generated by Django 4.0.6 on 2022-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_delete_faproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VALUE', '값'), ('RATIO', '비율')], max_length=5)),
                ('div', models.CharField(choices=[('STAB', '안정성'), ('PROF', '수익성'), ('GROW', '성장성'), ('ACTV', '활동성'), ('PROD', '생산성'), ('ETC', '기타')], max_length=4, null=True)),
                ('nm', models.CharField(max_length=256)),
                ('abbrev', models.CharField(blank=True, max_length=16)),
                ('lk', models.CharField(max_length=256)),
                ('oc', models.CharField(max_length=3)),
                ('syntax', models.TextField()),
                ('item', models.ManyToManyField(to='dashboard.faitem')),
                ('item_self', models.ManyToManyField(related_name='products', to='dashboard.faproduct')),
            ],
            options={
                'db_table': 'fa_product',
            },
        ),
    ]
