# Generated by Django 4.0.6 on 2022-07-27 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('5fe28389-09d5-47b1-adca-9dc2cf1fbb10'), max_length=128, unique=True),
        ),
    ]
