# Generated by Django 4.0.6 on 2022-08-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRatioValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqe', models.DateField(blank=True, null=True)),
                ('oc', models.CharField(max_length=3)),
                ('value', models.FloatField()),
                ('isLatest', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='ggdb.accountratio')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ratios', to='ggdb.corp')),
            ],
            options={
                'db_table': 'account_ratio_value',
                'get_latest_by': 'fqe',
            },
        ),
        migrations.CreateModel(
            name='AccountRatioValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevValue', models.FloatField(blank=True, null=True)),
                ('updatedAt', models.DateField(auto_now_add=True)),
                ('arv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ggdb.accountratiovalue')),
            ],
            options={
                'db_table': 'account_ratio_value_history',
                'get_latest_by': 'updatedAt',
            },
        ),
        migrations.AddIndex(
            model_name='accountratiovalue',
            index=models.Index(fields=['corp', 'ar', 'fqe', 'oc', 'isLatest'], name='account_rat_corp_id_bf0bb1_idx'),
        ),
    ]
