# Generated by Django 4.0.6 on 2022-08-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRatioValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.IntegerField()),
                ('bq', models.IntegerField()),
                ('method', models.CharField(max_length=3)),
                ('value', models.FloatField()),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='ggdb.accountratio')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ratios', to='ggdb.corp')),
            ],
            options={
                'db_table': 'account_ratio_value',
            },
        ),
        migrations.CreateModel(
            name='AccountRatioValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevValue', models.FloatField(blank=True, null=True)),
                ('updatedAt', models.DateField(auto_now_add=True)),
                ('arv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ggdb.accountratiovalue')),
            ],
            options={
                'db_table': 'account_ratio_value_history',
                'get_latest_by': 'updatedAt',
            },
        ),
    ]
