# Generated by Django 4.0.6 on 2022-08-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0002_accountratiovalue_accountratiovaluehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountratiovalue',
            options={'get_latest_by': ['by', 'bq']},
        ),
        migrations.RemoveField(
            model_name='accountratio',
            name='inspectResults',
        ),
    ]
