# Generated by Django 4.0.6 on 2022-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0002_accountratiovalue_accountratiovaluehistory_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fs',
            index=models.Index(fields=['corp', 'type', 'fqe'], name='cs_test'),
        ),
    ]
