# Generated by Django 4.0.6 on 2022-08-11 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0003_alter_accountratiovalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountratiovalue',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
