# Generated by Django 4.0.6 on 2022-09-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0003_fs_cs_test'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fs',
            name='fs_corp_id_71d20e_idx',
        ),
    ]
