# Generated by Django 4.0.6 on 2022-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0004_remove_fs_fs_corp_id_71d20e_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fs',
            index=models.Index(fields=['corp', 'type', 'fqe'], name='fs_corp_id_46c8fb_idx'),
        ),
    ]
