# Generated by Django 4.0.6 on 2022-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0004_accountratiovalue_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default='2022-07-28'),
            preserve_default=False,
        ),
    ]
