# Generated by Django 4.0.6 on 2022-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0005_corp_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountratiovalue',
            name='isLatest',
            field=models.BooleanField(default=False),
        ),
    ]
