# Generated by Django 4.0.6 on 2022-09-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0006_remove_fs_cs_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountratiovaluehistory',
            name='arv',
        ),
        migrations.DeleteModel(
            name='AccountRatioValue',
        ),
        migrations.DeleteModel(
            name='AccountRatioValueHistory',
        ),
    ]
