# Generated by Django 4.0.6 on 2022-08-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0006_accountratiovalue_islatest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountratiovalue',
            index=models.Index(fields=['corp', 'ar', 'by', 'bq', 'method', 'isLatest'], name='account_rat_corp_id_b7efb5_idx'),
        ),
    ]
