# Generated by Django 4.0.6 on 2022-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0007_remove_accountratiovaluehistory_arv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FsAccountLite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('oc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'fa_lite',
            },
        ),
        migrations.AddField(
            model_name='accountratio',
            name='items',
            field=models.ManyToManyField(to='ggdb.fsaccountlite'),
        ),
    ]
