# Generated by Django 4.0.6 on 2022-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0008_fsaccountlite_accountratio_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountratio',
            name='abbrev',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
