# Generated by Django 4.0.6 on 2022-09-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0009_accountratio_abbrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsaccountlite',
            name='batch',
            field=models.BooleanField(default=False),
        ),
    ]
