# Generated by Django 4.0.6 on 2022-09-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0010_fsaccountlite_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountratio',
            old_name='updatedAt',
            new_name='createdAt',
        ),
    ]
