# Generated by Django 4.0.6 on 2022-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0011_rename_updatedat_accountratio_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountratio',
            name='preset',
            field=models.BooleanField(default=False),
        ),
    ]
