# Generated by Django 4.0.6 on 2022-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0012_accountratio_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsdetail',
            name='allowMatch',
            field=models.BooleanField(default=False),
        ),
    ]
