# Generated by Django 4.0.6 on 2022-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdb', '0013_fsdetail_allowmatch'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fsdetail',
            name='fsdetail_account_3979b5_idx',
        ),
        migrations.AddIndex(
            model_name='fsdetail',
            index=models.Index(fields=['accountId', 'fs', 'account', 'createdAt'], name='fsdetail_account_b864a3_idx'),
        ),
    ]
